# Generated by Django 5.2.4 on 2025-08-05 12:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_azienda', models.CharField(max_length=200, verbose_name='Nome Azienda')),
                ('responsabile', models.CharField(max_length=100, verbose_name='Responsabile')),
                ('telefono_responsabile', models.CharField(max_length=20, verbose_name='Tel. Responsabile')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('email2', models.EmailField(blank=True, max_length=254, verbose_name='Email 2')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clienti',
                'ordering': ['nome_azienda'],
            },
        ),
        migrations.CreateModel(
            name='TipoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
                ('intervallo_manutenzione_giorni', models.IntegerField(default=365, verbose_name='Intervallo Manutenzione (giorni)')),
            ],
            options={
                'verbose_name': 'Tipo Componente',
                'verbose_name_plural': 'Tipi Componente',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('ruolo', models.CharField(choices=[('Administrator', 'Administrator'), ('Controlroom', 'Controlroom'), ('Operatore', 'Operatore')], default='Operatore', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cabina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome/Denominazione')),
                ('matricola', models.CharField(max_length=50, unique=True, verbose_name='Matricola')),
                ('guardiania', models.CharField(blank=True, max_length=100, verbose_name='Guardiania')),
                ('chiave', models.CharField(blank=True, max_length=50, verbose_name='N° Chiave')),
                ('pod', models.CharField(blank=True, max_length=50, verbose_name='POD')),
                ('telefono_guardiania', models.CharField(blank=True, max_length=20, verbose_name='Tel. Guardiania')),
                ('latitudine', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitudine')),
                ('longitudine', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitudine')),
                ('attiva', models.BooleanField(default=True, verbose_name='Attiva')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabine', to='gestione.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cabina',
                'verbose_name_plural': 'Cabine',
                'ordering': ['matricola'],
            },
        ),
        migrations.CreateModel(
            name='ManutenzioneOrdinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_manutenzione', models.DateField(verbose_name='Data Manutenzione')),
                ('tecnico', models.CharField(max_length=200, verbose_name='Tecnico')),
                ('completata', models.BooleanField(default=True, verbose_name='Completata')),
                ('note', models.TextField(blank=True, verbose_name='Note e Osservazioni')),
                ('controllo_generale', models.BooleanField(default=False, verbose_name='Controllo Generale')),
                ('pulizia_effettuata', models.BooleanField(default=False, verbose_name='Pulizia Effettuata')),
                ('controllo_collegamenti', models.BooleanField(default=False, verbose_name='Controllo Collegamenti')),
                ('test_funzionamento', models.BooleanField(default=False, verbose_name='Test Funzionamento')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('cabina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutenzioni_ordinarie', to='gestione.cabina')),
            ],
            options={
                'verbose_name': 'Manutenzione Ordinaria',
                'verbose_name_plural': 'Manutenzioni Ordinarie',
                'ordering': ['-data_manutenzione'],
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_installazione', models.DateField(blank=True, null=True, verbose_name='Data Installazione')),
                ('data_ultima_manutenzione', models.DateField(blank=True, null=True, verbose_name='Ultima Manutenzione')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('cabina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componenti', to='gestione.cabina')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.tipocomponente')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componenti',
            },
        ),
    ]
