# Generated by Django 5.2.4 on 2025-08-06 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManutenzioneProgrammata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('semestrale', 'Ordinaria Semestrale'), ('annuale', 'Ordinaria Annuale'), ('straordinaria', 'Straordinaria')], default='semestrale', max_length=20)),
                ('data_programmata', models.DateField()),
                ('data_completamento', models.DateField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('programmata', 'Programmata'), ('in_corso', 'In Corso'), ('completata', 'Completata'), ('annullata', 'Annullata')], default='programmata', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('cabina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutenzioni', to='gestione.cabina')),
                ('creata_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutenzioni_create', to=settings.AUTH_USER_MODEL)),
                ('operatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manutenzione Programmata',
                'verbose_name_plural': 'Manutenzioni Programmate',
                'ordering': ['-data_programmata'],
            },
        ),
        migrations.DeleteModel(
            name='ManutenzioneOrdinaria',
        ),
    ]
