# Generated by Django 5.2.4 on 2025-08-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0002_manutenzioneprogrammata_delete_manutenzioneordinaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabina',
            name='fonte',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fonte energetica'),
        ),
    ]
