# Generated by Django 5.2.4 on 2025-08-07 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0003_cabina_fonte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome servizio')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name': 'Servizio',
                'verbose_name_plural': 'Servizi',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CabinaServizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scadenza', models.DateField(verbose_name='Data scadenza')),
                ('cabina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servizi_assoc', to='gestione.cabina')),
                ('servizio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.servizio')),
            ],
            options={
                'verbose_name': 'Servizio assegnato',
                'verbose_name_plural': 'Servizi assegnati alle cabine',
                'unique_together': {('cabina', 'servizio')},
            },
        ),
    ]
