# Generated by Django 5.2.4 on 2025-08-26 14:08

import django.core.validators
import django.db.models.deletion
import gestione.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0004_servizio_cabinaservizio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCompilato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_snapshot', models.JSONField()),
                ('dati', models.JSONField(default=dict)),
                ('stato', models.CharField(choices=[('bozza', 'Bozza'), ('inviato', 'Inviato')], default='bozza', max_length=20)),
                ('compilato_il', models.DateTimeField(auto_now_add=True)),
                ('cabina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestione.cabina')),
                ('compilato_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_compilati', to=settings.AUTH_USER_MODEL)),
                ('manutenzione', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='gestione.manutenzioneprogrammata')),
            ],
        ),
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('file', models.ImageField(upload_to=gestione.models.report_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='gestione.reportcompilato')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True)),
                ('frequenza', models.CharField(blank=True, max_length=20)),
                ('versione', models.PositiveIntegerField(default=1)),
                ('attivo', models.BooleanField(default=True)),
                ('schema', models.JSONField(default=dict)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('creato_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_template_creati', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reportcompilato',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestione.reporttemplate'),
        ),
    ]
