# Generated by Django 5.2.4 on 2025-08-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0005_reportcompilato_reportattachment_reporttemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='cabine',
            field=models.ManyToManyField(blank=True, related_name='report_templates', to='gestione.cabina'),
        ),
    ]
