# Generated by Django 5.2.4 on 2025-08-28 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0006_reporttemplate_cabine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manutenzioneprogrammata',
            options={'ordering': ['data_completamento'], 'verbose_name': 'Manutenzione Programmata', 'verbose_name_plural': 'Manutenzioni Programmate'},
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='cabine',
        ),
        migrations.AddField(
            model_name='cabina',
            name='template_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabine_assegnate', to='gestione.reporttemplate', verbose_name='Template report'),
        ),
    ]
