# Generated by Django 5.2.4 on 2025-09-15 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestione", "0007_alter_manutenzioneprogrammata_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PianoManutenzione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("semestrale_annuale", "Semestrale + Annuale"),
                            ("annuale_only", "Solo Annuale"),
                            ("spot", "Spot"),
                            ("mensile_lite_annuale", "Mensile Lite + Annuale"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "durata_contrattuale_mesi",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Durata contrattuale (mesi)"
                    ),
                ),
                (
                    "cabina",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="piano_manutenzione",
                        to="gestione.cabina",
                    ),
                ),
            ],
        ),
    ]
