# Generated by Django 5.2.4 on 2025-09-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0008_pianomanutenzione'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabina',
            name='societa_proprietaria',
            field=models.CharField(blank=True, max_length=100, verbose_name='Società proprietaria'),
        ),
    ]
