# Generated by Django 5.2.4 on 2025-09-24 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0009_cabina_societa_proprietaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutenzioneprogrammata',
            name='stato',
            field=models.CharField(choices=[('programmata', 'Programmata'), ('completata', 'Completata'), ('inviata', 'Inviata'), ('fatturata', 'Fatturata')], default='programmata', max_length=20),
        ),
        migrations.AlterField(
            model_name='manutenzioneprogrammata',
            name='tipo',
            field=models.CharField(choices=[('semestrale', 'Ordinaria Semestrale'), ('annuale', 'Ordinaria Annuale'), ('mensile', 'Mensile Lite'), ('spot', 'Spot / Extra')], default='semestrale', max_length=20),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('priorita', models.CharField(choices=[('critica', 'Critica'), ('alta', 'Alta'), ('normale', 'Normale')], default='normale', max_length=10)),
                ('scadenza', models.DateField()),
                ('silenziato', models.BooleanField(default=False)),
                ('posticipato_a', models.DateField(blank=True, null=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('cabina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.cabina')),
                ('componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestione.componente')),
            ],
        ),
    ]
